[package]
name = "monster"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
incremental = true

[dependencies]
raylib = "3.5"
rand = "0.8"
